//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchEngine.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .I 001
        ///.D
        ///what &quot;similarity laws&quot; must be obeyed when constructing aeroelastic models
        ///of heated high speed aircraft .
        ///.I 002
        ///.D
        ///what are the structural and aeroelastic problems associated with flight
        ///of high speed aircraft .
        ///.I 023
        ///.D
        ///how can the aerodynamic performance of channel flow ground effect
        ///machines be calculated .
        ///.I 157
        ///.D
        ///in summarizing theoretical and experimental work on the behaviour of a
        ///typical aircraft structure in a noise environment is it possible to
        ///develop a design proce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cran_information_needs {
            get {
                return ResourceManager.GetString("cran_information_needs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a	hence	see
        ///able	her	seeing
        ///about	here	seem
        ///above	hereafter	seemed
        ///abroad	hereby	seeming
        ///according	herein	seems
        ///accordingly	here&apos;s	seen
        ///across	hereupon	self
        ///actually	hers	selves
        ///adj	herself	sensible
        ///after	he&apos;s	sent
        ///afterwards	hi	serious
        ///again	him	seriously
        ///against	himself	seven
        ///ago	his	several
        ///ahead	hither	shall
        ///ain&apos;t	hopefully	shan&apos;t
        ///all	how	she
        ///allow	howbeit	she&apos;d
        ///allows	however	she&apos;ll
        ///almost	hundred	she&apos;s
        ///alone	i	should
        ///along	i&apos;d	shouldn&apos;t
        ///alongside	ie	since
        ///already	if	six
        ///also	i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StopwordList {
            get {
                return ResourceManager.GetString("StopwordList", resourceCulture);
            }
        }
    }
}
